### ISSUE TITLE
Error message when trying to set a requirement option with a dot in the name

### ISSUE THREAD

**Issue by JPGygax68** [lasote/conan-boost#10]
I'm still trying to get my executable package to link with a debug build of boost. I tried setting the following option in my conanfile:
```
  default_options = "Boost:shared=False", "Boost:compiler.runtime=MDd"
```
but when I run `conan install`, I get:
```
ERROR: d:\Projects\GPC\FontRasterizer.new\rasterizer\conanfile.py: Error while initializing options. 'NoneType' object has no attribute 'runtime'
```

Is my syntax wrong ?

EDIT: I just realized this may be the wrong place to ask this question. Please tell me if you think I should re-post this in conan-io.

**Comment by lasote** [comment]
Hi! compiler and compiler.runtime are not options, are settings.
It cannot be set in a conanfile because as they are settings are considered a "global" thing, so they have to be specified in the conan install command:

conan install -s compiler="Visual Studio" -s compiler.runtime="MDd" 

Or change the defaults in your ~/.conan/conan.conf

**Comment by lasote** [comment]
About the place of make this question, yes, should be better to move it to conan.io repository.
Thanks!

**Comment by SSE4** [comment]
This issue was moved to conan-community/community#86
