### ISSUE TITLE
Some help regarding conanfile.py

### ISSUE THREAD

**Issue by Manu343726** [lasote/conan-boost#4]
Hello my name is Palmeritaman, I'm new to conan.io.

Ok seriously, I was checking out the conanfile.py of this package to get into conan packaging and there are some points that I don't get:
- There's a comment [in line 28](https://github.com/lasote/conan-boost/blob/master/conanfile.py#L28) stating "_config is called twice, one before receive the upper dependencies and another before_" what this exactly means?

**Comment by lasote** [comment]
Yeah Palmerita man, it's a tricky think that we don't really know how to do it better. 
Conanfile config method is evaluated two times. Why? because of the "pescadilla que se muerde la cola" heheheh. We need the config to call the upstream packages config method but our config could depend on upstream variables, so I use these tricky counter to know if upstream deps have setted something.

**Comment by Croydon** [comment]
Can be closed?

**Comment by lasote** [comment]
Yes, thanks @Croydon , that problem was solved in conan with the config_options methods.
