### ISSUE TITLE
Boost fails build on clang and gcc for lasote/

### ISSUE THREAD

**Issue by acgetchell** [lasote/conan-boost#46]
Here's the link to the Travis build:

https://travis-ci.org/acgetchell/causal-sets-explorer/builds/235856516

Compare with earlier build:

https://travis-ci.org/acgetchell/causal-sets-explorer/builds/234119331

**Comment by lasote** [comment]
Hi! The build from my boost packages failed because of a failure downloading sources, please try again and report if it's still failing!

Thanks Adam

**Comment by acgetchell** [comment]
Hello! It works now with clang, apple-clang, and Visual Studio 2015. It fails on gcc.

Main project:
https://github.com/acgetchell/causal-sets-explorer

Travis-CI:
https://travis-ci.org/acgetchell/causal-sets-explorer/builds/236757944

AppVeyor:
https://ci.appveyor.com/project/acgetchell/causal-sets-explorer

**Comment by lasote** [comment]
Wow, it raises an error that probably is related with memory management: ``g++: internal compiler error: Killed (program cc1plus)``. It's probably related with install modern gcc like 6.2 in a very old image (with native 4.8) in these cases we recommend to build with a docker image with the native compiler installed. I'm going to take a look and document how you can do it, ok? Otherwise I have not a clue about the error, but I bet that can be the problem.

**Comment by Croydon** [comment]
Seems to be done.
